export const conversationActions = {
    SET_CONVERSATIONS: 'SET_CONVERSATIONS',
    SET_SELECTED_CONVERSATION: 'SET_SELECTED_CONVERSATION',
    SET_MESSAGES: 'SET_MESSAGES',
    ADD_MESSAGE: 'ADD_MESSAGE',
    SET_INPUT_VALUE: 'SET_INPUT_VALUE'
}
